version: '3.7'
services:
  nats:
    image: 'nats:2.1.0'
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
  nats-streaming:
    image: 'nats-streaming:0.16.2'
    ports:
      - "4223:4222"
      - "8223:8222"
  grpc-role-exchange-demo:
    image: dotnetcore-nats-play/subscribe
    depends_on:
      - nats
      - nats-streaming