version: '3.7'
services:
  nats:
    image: 'nats:2.1.0'
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
  nats-streaming:
    image: 'nats-streaming:0.16.2'
    ports:
      - "4223:4222"
      - "8223:8222"
  nats-subscribe:
    image: dotnetcore-nats-play/subscribe
    depends_on:
      - nats
      - nats-streaming
    environment:
      - VERBOSE=True
      - SUBJECT=foo
      - URL=nats://nats:4222
      - QUEUE_GROUP=subscribe-group

  nats-replier:
    image: dotnetcore-nats-play/replier
    depends_on:
      - nats
      - nats-streaming
    environment:
      - VERBOSE=True
      - SUBJECT=dog
      - URL=nats://nats:4222
      - QUEUE_GROUP=replier-group

  stan-sub:
    image: dotnetcore-nats-play/stan-sub
    depends_on:
      - nats
      - nats-streaming
    environment:
      - VERBOSE=True
      - SUBJECT=dog
      - URL=nats://nats-streaming:4222
      - QUEUE_GROUP=stan-sub-group
      - DURABLE_NAME=stan-sub-durable